#!/usr/bin/env ruby

require 'bundler/setup'
require 'markdown-ui'

puts "Hit RETURN three times to parse."

def multi_gets all_text=""
  while all_text << STDIN.gets
    if all_text["\n\n\n"]
      return all_text
    elsif all_text[/^exit|^quit|^bye/]
      exit 0
    else
      print "# "
    end
  end
end

def prompt(*args)
    print(*args)
    multi_gets
end

while m = prompt("# ")
  parser = Redcarpet::Markdown.new(MarkdownUI::Renderer, quote: true, tables: true, xhtml: true)
  puts <<-EOF

    #{parser.render(m)}
  EOF
end
